apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: cm9vdA== # base64 encoded 'root'
  mysql-password: Tml0eWFvYmplY3RAMTIz # base64 encoded 'Nityaobject@123'

